general.import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"  # Replace with your installed font
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
